#!/usr/bin/env ruby

$: << File.expand_path('../lib', File.dirname(__FILE__))
$KCODE = 'u'

require 'rubygems'
require 'drb'
require 'oddb/config'
require 'oddb/drugs'
require 'oddb/persistence'
require 'oddb/util'
require 'encoding/character/utf-8'

system = DRb::DRbObject.new(nil, ODDB.config.server_url)
DRb.start_service
begin
  system.peer_cache ODBA.cache
  module ODDB
    module Util
      Updater.import_gkv
    end
  end
ensure
  system.unpeer_cache ODBA.cache
end
