#!/usr/bin/env ruby

$: << File.expand_path('../lib', File.dirname(__FILE__))
$KCODE = 'u'

require 'rubygems'
require 'oddb/util/job'

module ODDB
  module Util
    opt = {}
    if ARGV[0].split("=")[0] == "pdf"
      opt = {:pdf => ARGV[0].split("=")[1]}
    end
    Job.run do 
      Updater.import_gkv opt
    end
  end
end
