#!/usr/bin/env ruby

$: << File.expand_path('../lib', File.dirname(__FILE__))
$KCODE = 'u'

require 'rubygems'
require 'oddb/util/job'

$opts = if ARGV[0] != "" 
          {:pdf => ARGV[0]} 
       else
          {}
       end
module ODDB
  module Util
    Job.run do 
      Updater.import_gkv $opts
    end
  end
end
